name: dishtv_agent_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.5
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.19.0
  fl_chart: ^1.0.0
  pdf: ^3.11.0
  printing: ^5.12.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" # अपनी लोगो फ़ाइल का सही रास्ता दें
  min_sdk_android: 21 # optional
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # optional
  macos:
    generate: true

flutter:
  uses-material-design: true
